test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/Cargo.toml
trie-root/Cargo.toml

This update codec and make new release of trie-bench and reference-tri
I only need trie-bench release for substrate so I don't know if we release a new one for reference-trie also.
as it is only dev depencencies of trie-root and trie-db we don't need to update them.

update codec and new release

---

hash-db/Cargo.toml
hash-db/src/lib.rs
hash256-std-hasher/Cargo.toml
memory-db/Cargo.toml
memory-db/src/lib.rs
test-support/keccak-hasher/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
test-support/trie-standardmap/Cargo.toml
trie-db/Cargo.toml
trie-db/src/fatdb.rs
trie-db/src/lib.rs
trie-db/src/lookup.rs
trie-db/src/sectriedb.rs
trie-db/src/triedb.rs
trie-db/src/triedbmut.rs
trie-root/Cargo.toml

This lays out the traits needed to solve https://github.com/paritytech/substrate/issues/872#issuecomment-436816629, to support multiple hashing algorithms in multi-trie.
Because we can't know how many children tries are created, multi-trie needs to write all hashdb values into a single storage. To support multiple hash algorithms, the length of the hash might also be different, while the underlying data store might expect a fixed length hash. With traits in this PR, we can fix both of the issues:
* Pass `PlainDB` reference in children delta trie root generation. The generation function wraps `PlainDB` into another `HashDB` of the targeted hash algorithm to continue the operation.
* If the generation function is really sure that targeted hash and original hash have the same length (and …

PlainDB for multi-trie multi-hash

---

hash-db/Cargo.toml
hash-db/src/lib.rs
hash256-std-hasher/Cargo.toml
memory-db/Cargo.toml
memory-db/src/lib.rs
test-support/keccak-hasher/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/reference-trie/src/lib.rs
test-support/trie-bench/Cargo.toml
test-support/trie-bench/src/lib.rs
test-support/trie-standardmap/Cargo.toml
trie-db/Cargo.toml
trie-db/src/fatdb.rs
trie-db/src/fatdbmut.rs
trie-db/src/lookup.rs
trie-db/src/nibbleslice.rs
trie-db/src/recorder.rs
trie-db/src/sectriedb.rs
trie-db/src/sectriedbmut.rs
trie-db/src/triedb.rs
trie-db/src/triedbmut.rs
trie-root/Cargo.toml

For some applications, such as substrate it is desirable to have each node to be unique in the trie. So that the same node can't be inserted into two separate branches of the same trie. This simplifies implementation of node storage quite a lot, since it removes the need for reference counting.
In ethereum the uniqueness is already guaranteed by the fact that the keys are hashes and each value ends up in a leaf node with a long random partial key. In Substrate this is not the case, as the keys are plain.
This PR introduces an additional parameter for `HashDB` functions that takes encoded partial node key. This allows for separating colliding nodes on the database levels, and for more efficient database implementation. E.g. The nodes that are close to each other in the trie may be grouped …

Node key prefixes in the database

---

trie-db/Cargo.toml
trie-db/src/triedb.rs

Trie iteration was not implemented correctly in #12 
Also switched tests to use prefixed storage.

Fix iteration for prefixed storage

---

hash-db/Cargo.toml
hash-db/src/lib.rs
hash256-std-hasher/Cargo.toml
memory-db/Cargo.toml
memory-db/src/lib.rs
test-support/keccak-hasher/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
test-support/trie-standardmap/Cargo.toml
trie-db/Cargo.toml
trie-db/src/fatdb.rs
trie-db/src/lib.rs
trie-db/src/lookup.rs
trie-db/src/nibbleslice.rs
trie-db/src/node.rs
trie-db/src/node_codec.rs
trie-db/src/recorder.rs
trie-db/src/sectriedb.rs
trie-db/src/triedb.rs
trie-db/src/triedbmut.rs
trie-root/Cargo.toml

This PR allows trie to run in no_std mode : eg https://github.com/paritytech/substrate/compare/master...cheme:no_std-trie 
It requires 'alloc' so it is no_std for nightly only.
This replies to https://github.com/paritytech/substrate/issues/1574 .
For memory-db and trie I use 'hashmap_core' crate, this is not a very good choice as 'hashbrown' is more maintained, and long term it should be replaced by 'hashbrown'. I did not use 'hashbrown' because the way we switch to 'no_std' is done through feature declaration (feature 'nightly'), that means that I have to propagate the feature up to the no_std building crate (see commit history of this pr) which is very awkward.
Versioning update is minor and global (I believe it is a choice to keep versioning constistent between trie subproject).
I kept …

No std support for trie

---

test-support/trie-standardmap/Cargo.toml

needed for https://github.com/paritytech/parity-ethereum/pull/10670:
there are some problems compiling `criterion` > `0.2.5`:
```rust
error[E0599]: no method named `fill_bytes` found for type `std::cell::RefMut<'_, rand_os::OsRng>` in the current scope
--> /path/to/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.11/src/stats/rand_util.rs:16:24
|
16 |         r.borrow_mut().fill_bytes(&mut seed);
|                        ^^^^^^^^^^
|
= help: items from traits can only be used if the trait is in scope
= note: the following trait is implemented but not in scope, perhaps add a `use` for it:
`use rand_os::rand_core::RngCore;`
```

[trie-standardmap] remove unused dep; bump version to 0.12.3

---

hash-db/Cargo.toml
hash-db/src/lib.rs
hash256-std-hasher/Cargo.toml
memory-db/Cargo.toml
memory-db/src/lib.rs
test-support/keccak-hasher/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
test-support/trie-standardmap/Cargo.toml
trie-db/Cargo.toml
trie-root/Cargo.toml

This PR deprecates heapsize (currently keeping it behind an optional feature).
It uses parity-util-mem instead.
~~This PR can be reviewed but **cannot merge** until PR ~~https://github.com/paritytech/parity-common/pull/93~~ https://github.com/paritytech/parity-common/pull/94 get approved and the crate published.
The versioning was not yet updated.~~

Deprecate heapsize

---

test-support/reference-trie/Cargo.toml
test-support/reference-trie/src/lib.rs
test-support/trie-bench/Cargo.toml
test-support/trie-bench/src/lib.rs
trie-db/Cargo.toml
trie-root/Cargo.toml

Needed for the https://github.com/paritytech/substrate/pull/2855.

Update codec version

---

hash-db/Cargo.toml
hash-db/src/lib.rs
hash256-std-hasher/Cargo.toml
memory-db/Cargo.toml
memory-db/src/lib.rs
test-support/keccak-hasher/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
test-support/trie-standardmap/Cargo.toml
trie-db/Cargo.toml
trie-db/src/fatdb.rs
trie-db/src/fatdbmut.rs
trie-db/src/lib.rs
trie-db/src/lookup.rs
trie-db/src/sectriedb.rs
trie-db/src/sectriedbmut.rs
trie-db/src/triedb.rs
trie-db/src/triedbmut.rs
trie-root/Cargo.toml

Version 12.3 broke no_std compatibility.
This PR fixes that.
The PR also removes some warning (add 'dyn' info on types).

fix no_std build for memory-db.

---

hash-db/Cargo.toml
hash256-std-hasher/Cargo.toml
memory-db/Cargo.toml
test-support/keccak-hasher/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
test-support/trie-standardmap/Cargo.toml
trie-db/Cargo.toml
trie-db/src/triedb.rs
trie-root/Cargo.toml

This pr update parity-util-mem to 0.2 (no clear_on_drop dep).
And align versioning between all crates.
Also a test format fix.

Parity util mem update and verision alignment

---

test-support/reference-trie/Cargo.toml
test-support/reference-trie/src/lib.rs
test-support/trie-bench/Cargo.toml
test-support/trie-bench/src/lib.rs

We just need new version of trie-bench.
and reference-trie desn't need a major version bump because last version is not published

Update codec + new release of trie-bench

---

hash-db/src/lib.rs

Looks like this is an unnecessary feature.

Remove feature(core-intrinsics)

---

test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml

While publishing 0.15, I realize a 0.15 for bench has already been published.
Therefore this PR update bench to 0.16.

update bench version for publishing.

---

Cargo.toml

So that its tests are included when running `cargo test --all`.

Add reference-trie to cargo workspace members

---

test-support/reference-trie/src/lib.rs
trie-db/src/iterator.rs
trie-db/src/lib.rs
trie-db/src/triedb.rs

This is a new trie iterator that iterates over the actual trie nodes, not just the values. I have wanted this functionality before for measuring information about the trie, such as number and size of internal nodes. The motivation now is for proof construction over nodes recorded out of order. With this iterator, one could use the recorder over the full trie, build an incomplete `MemoryDB` with the recorded nodes, then traverse those in order to construct a compact proof.
This change is completely backwards compatible and the old `TrieDBIterator` is now implemented using the `TrieDBNodeIterator`.

Implement a pre-order iterator over trie nodes.

---

test-support/reference-trie/src/lib.rs
trie-db/benches/bench.rs
trie-db/src/iterator.rs
trie-db/src/node.rs
trie-db/src/node_codec.rs
trie-db/src/triedb.rs

The goal of this change is to remove some of the duplication and inefficiency of `OwnedNode`. `OwnedNode` is a parallel data structure to `Node` that is constructed by copying a lot of data into new allocations. Notably, an `OwnedNode` cannot easily be converted to a `Node` because of alignment issues between `NibbleVec`, which `OwnedNode` uses to represent partial keys, and `NibbleSlice`, which `Node` uses to represent partial keys.
The idea head is for `OwnedNode` to just store an encoded trie node along with a blueprint for quickly decoding into a node. When an encoded node is first decoded, instead of creating a `Node` directly, which has a lifetime, one can construct a `NodePlan` which is an owned structure and can be used to quickly create Nodes thereafter. The `OwnedNode` can be …

Implement OwnedNode using a node decode plan.

---

memory-db/Cargo.toml
trie-db/Cargo.toml

This will ensure that every build uses the same `ahash` seed, instead of a compile-time randomized one (which is now the default - see https://github.com/rust-lang/hashbrown/issues/124, https://github.com/rust-lang/hashbrown/pull/125, https://github.com/tkaitchuck/aHash/pull/18 and https://github.com/tkaitchuck/aHash/pull/25 for more details/background).
(The other such update PR needed is https://github.com/paritytech/finality-grandpa/pull/90).

Disable "ahash-compile-time-rng" feature in hashbrown.

---

test-support/reference-trie/src/lib.rs
trie-db/src/iterator.rs
trie-db/src/lib.rs
trie-db/src/lookup.rs
trie-db/src/node.rs
trie-db/src/node_codec.rs
trie-db/src/triedb.rs
trie-db/src/triedbmut.rs

Currently, branch and extension nodes just have a byte slice reference to the child nodes and one uses the `NodeCodec::try_decode_hash` method to determine whether it is a hash or an inline node reference. Instead, we make this an explicit part of the decoded Node structure to simply code and make the codec more flexible. For example, we can stop encoding the length of the hashes inside branch nodes and instead use another bitfield inside branch nodes to indicate whether each child is a hash or inline reference, which should save space.
This is another breaking change to NodeCodec building on #34.

Add NodeHandle enum for node references within Node

---

memory-db/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/Cargo.toml
trie-root/Cargo.toml

Bump from 0.15 to 0.16 after breaking changes to trie-db crate.

Bump trie-db and reference-trie crates to 0.16.0.

---

test-support/reference-trie/src/lib.rs
trie-db/src/iter_build.rs
trie-db/src/lib.rs
trie-db/src/nibble/nibblevec.rs
trie-db/src/trie_codec.rs
trie-db/src/triedbmut.rs

As per module doc:
```rust
//! Compact encoding/decoding functions for partial Merkle-Patricia tries.
//!
//! A partial trie is a subset of the nodes in a complete trie, which can still be used to
//! perform authenticated lookups on a subset of keys. A naive encoding is the set of encoded nodes
//! in the partial trie. This, however, includes redundant hashes of other nodes in the partial
//! trie which could be computed directly. The compact encoding strips out all hash child
//! references to other nodes in the partial trie and replaces them with empty inline references,
//! indicating that the child reference is omitted. The nodes are then ordered in pre-order
//! traversal order so that the full nodes can be efficiently reconstructed recursively. Note that
//! hash references to …
```

Implement compact encoding scheme for partial tries.

---

hash-db/src/lib.rs
trie-db/Cargo.toml
trie-db/src/fatdb.rs
trie-db/src/fatdbmut.rs
trie-db/src/iter_build.rs
trie-db/src/lib.rs
trie-db/src/nibble/mod.rs
trie-db/src/nibble/nibbleslice.rs
trie-db/src/nibble/nibblevec.rs
trie-db/src/node.rs
trie-db/src/sectriedb.rs
trie-db/src/sectriedbmut.rs
trie-db/src/triedb.rs
trie-db/src/triedbmut.rs

The `elastic-array` crate is a fine piece of software but it'd be good to prefer crates that are commonly used in the ecosystem and likely to be well maintained. `smallvec` is at `v1.0` and generally well-regarded.
Unfortunately as `DBValue` is part of the public API of `trie-db`, this is a breaking change so changing this implies annoying busy-work in consuming code.

Replace ElasticArray with SmallVec

---

memory-db/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/Cargo.toml
trie-db/fuzz/Cargo.toml
trie-db/src/fatdbmut.rs
trie-db/src/iter_build.rs
trie-db/src/triedb.rs
trie-root/Cargo.toml

Cloned #47 to make last change.

Prepare versioning for 0.18 crates (no elastic array) (clone off #47)

---

.gitignore
test-support/reference-trie/src/lib.rs
trie-db/benches/bench.rs
trie-db/fuzz/Cargo.toml
trie-db/fuzz/fuzz_targets/trie_proof_invalid.rs
trie-db/fuzz/fuzz_targets/trie_proof_valid.rs
trie-db/fuzz/src/lib.rs
trie-db/src/lib.rs
trie-db/src/nibble/leftnibbleslice.rs
trie-db/src/nibble/mod.rs
trie-db/src/proof/generate.rs
trie-db/src/proof/mod.rs
trie-db/src/proof/verify.rs
trie-db/src/triedbmut.rs

Generation and verification of compact proofs for Merkle-Patricia tries. These have the benefit over the compact trie encoding of omitting the values from the proof data. Apart from being a more standard logical separation for a proof interface, this can result in bandwidth savings if the verifier already has the values. For example, they may request a proof that a value at a key is the same as it is with respect to another trie root.
Using this module, it is possible to generate a logarithmic-space proof of inclusion or non-inclusion of certain key-value pairs in a trie with a known root. The proof contains information so that the verifier can reconstruct the subset of nodes in the trie required to lookup the keys. The trie nodes are not included in their entirety as data which the …

Introduce module in trie-db for generating/verifying trie proofs.

---

test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/Cargo.toml
trie-root/Cargo.toml

Since #45 was merged, preparing for publish.

Bump trie-db version to v0.19.0

---

trie-db/src/lib.rs

`TrieError` should implement `Debug` in `no_std` as well. The compiler
can optimize it away if not required, but it enables us to use `expect`
in `no_std`. This is helpful for Cumulus, where I currently have a
custom `unwrap_trie_error` function with panics.

Implement `Debug` for `TrieError` in `no_std`

---

trie-db/Cargo.toml
trie-db/src/triedbmut.rs

It's quite annoying to see long listings of value bytes (by default printed one-byte-per-line) when running with `trace`. This PR displays values as hex-encoded items, but keeps them on a single line.
~I'm waiting for https://github.com/debris/rustc-hex/pull/3 to avoid allocating intermediate `String` when displaying, so marking this PR as a draft now.~ Done.

Display trace messages with hex-encoded items.

---

memory-db/benches/bench.rs

This PR allows `trie` to compile with recent nightly.

fix for memory-db-bench (error[E0373])

---

memory-db/Cargo.toml
memory-db/src/lib.rs
trie-db/Cargo.toml
trie-db/src/proof/generate.rs

The `no_std` builds look broken:
* The broken build in `memory-db` may be reproduced with `cargo build --no-default-features`
* The broken build in `trie-db` for some reason is only triggered while building substrate.
Probably this commit should bump the patchversion to `0.19.2`?

Fixes no_std builds for memory-db and trie-db.

---

trie-db/Cargo.toml

this should drop dependency on `rand_isaac` and alleviate possible cargo feature leaking to no-std binaries

Upgrade to rand 0.7

---

trie-db/Cargo.toml

`cd trie-db && cargo check --no-default-features`

trie-db: fix std feature leaking

---

test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml

Bumps a `trie-bench` version so paritytech/substrate#4646 hopefully builds

trie-bench version 0.19.0

---

memory-db/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/Cargo.toml
trie-db/src/triedbmut.rs
trie-root/Cargo.toml

`death_row` currently records deletions with incorrect partial keys. This leads to a lot of junk in the database.

Fix node deletion

---

trie-db/src/lib.rs

`clippy` complains that `description` is deprecated in `Error`. This PR removes it to silence `clippy`.

remove deprecated `description` method for TrieError

---

trie-db/src/lib.rs

Revert "remove deprecated `description` method for TrieError"

---

memory-db/src/lib.rs
test-support/reference-trie/src/lib.rs
trie-db/src/iter_build.rs
trie-db/src/iterator.rs
trie-db/src/triedb.rs
trie-db/src/triedbmut.rs

This PR removes all clippy warnings pertaining to [this](https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy) issue, in which `clone` is called when the object supports the `Copy` trait.

clippy: do not clone a Copy-able var

---

memory-db/Cargo.toml
trie-db/Cargo.toml

This upgrades the `hashbrown` dependency and also removes `ahash` from
`memory-db`. This `ahash` dependency actually lead to non-deterministic
builds, as it enabled the `compile-time-rng` feature. As `memory-db`
only included this dependency to pin the version, we can safely remove it.

Upgrade hasbrown for `memory-db` and `trie-db`

---

memory-db/CHANGELOG.md
memory-db/Cargo.toml
test-support/reference-trie/CHANGELOG.md
test-support/reference-trie/Cargo.toml
test-support/trie-bench/CHANGELOG.md
test-support/trie-bench/Cargo.toml
trie-db/CHANGELOG.md
trie-db/Cargo.toml
trie-db/src/lib.rs
trie-root/Cargo.toml

Releasing the hasbrown fix as patch version wasn't a good idea as it breaks the build if we not upgrade the other dependencies. To prevent this, we increment the `trie-db` version and yank the old version.

Increment trie-db to prevent build errors

---

memory-db/CHANGELOG.md
memory-db/Cargo.toml
memory-db/src/lib.rs
memory-db/src/malloc_size_of.rs
test-support/reference-trie/Cargo.toml
test-support/trie-bench/CHANGELOG.md
test-support/trie-bench/Cargo.toml
trie-db/Cargo.toml
trie-root/Cargo.toml

We can not use the `MemCounter` in wasm, because `parity-util-mem`
panics ;) Instead we just use the `NoopTracker` in wasm.

Fix memory-db in wasm

---

memory-db/src/lib.rs

In OpenEthereum when snapshotting starts we are restricting new blocks to be saved into our database and we are using MemoryDB to temporarily save them in RAM. And MemoryDB gets really large (13gb is my last count) and this is okay, but after snapshot passes there is no way to shrink back HashMap that is inside of MemoryDB.
This is a simple function that will allow us to do garbage collection and shrink MemoryDB.

Add shrink_to_fit to MemoryDB

---

trie-db/Cargo.toml

Fixes #95.
I don't know how to test this in CI properly, because cargo feature resolution in combination with additive features always selects this feature of `hashbrown`.
Tested this locally with a `path` dependency on `trie-db`.

trie-db: use ahash feature of hashbrown

---

hash256-std-hasher/Cargo.toml
memory-db/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/Cargo.toml
trie-root/Cargo.toml

Signed-off-by: koushiro <koushiro.cqx@gmail.com>
need to release a new version of `trie-bench`

*: update criterion to v0.3

---

memory-db/CHANGELOG.md
memory-db/Cargo.toml
test-support/reference-trie/CHANGELOG.md
test-support/reference-trie/Cargo.toml
test-support/reference-trie/src/lib.rs
test-support/trie-bench/CHANGELOG.md
test-support/trie-bench/Cargo.toml
trie-db/test/Cargo.toml
trie-root/test/Cargo.toml

once it is merge I will publish and add tags

update to codec 2.0

---

trie-db/Cargo.toml
trie-db/src/iterator.rs
trie-db/src/triedb.rs
trie-db/test/src/triedb.rs

When using 'seek' on a prefixed iterator, prefix context is lost.
This pr adds a function 'prefix_then_seek' for this usecase.

Seek for prefixed iterator.

---

test-support/reference-trie/CHANGELOG.md
test-support/reference-trie/Cargo.toml
test-support/trie-bench/CHANGELOG.md
test-support/trie-bench/Cargo.toml

Part of https://github.com/paritytech/substrate/pull/9163.
This is a pre-release so that we can experiment a bit more with the `MaxEncodedLen` trait if needed, but since Cargo wants pre-releases to be explicitly specified (and are not considered automatically SemVer-compatible), this does exactly that. That's also needed so that we can select a single `parity-scale-codec` version in the Substrate crate graph.

Bump parity-scale-codec to 2.2.0-rc.1

---

memory-db/Cargo.toml
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml

Companion for https://github.com/paritytech/parity-common/pull/556

Update requirement for parity-util-mem

---

trie-db/src/triedbmut.rs
trie-db/test/src/triedbmut.rs

There was an issue with prefix calculation when calling `fix` function recursively for extension (on removal).
The combination of db using node prefix and trie layout with extension is not something that I believe is use anywhere.

Fix prefix for extension implementation

---

README.md

I just noticed the CI badge still refers to Travis CI which was dropped at https://github.com/paritytech/trie/pull/113.
So, I think it's good to use the badge for GitHub Actions badge instead.
| Before | After |
| --- | --- | 
| <img width="144" alt="image" src="https://user-images.githubusercontent.com/6782666/132119766-401c0836-755e-493e-af62-7388ed082718.png"> | <img width="156" alt="image" src="https://user-images.githubusercontent.com/6782666/132119772-3b50b653-1029-4416-b877-b4746590fbca.png"> |

Use GitHub Actions CI badge

---

trie-db/src/triedbmut.rs

The trie trace logs use one line per byte, making it unreadable.  
Instead put it in one line. 
There is no test for this but I tested it in the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b19c89e680851fdbdf683b605d2b8227).

Fix hex trace output

---

test-support/reference-trie/src/lib.rs
test-support/trie-bench/src/lib.rs
trie-db/CHANGELOG.md
trie-db/src/fatdb.rs
trie-db/src/fatdbmut.rs
trie-db/src/lib.rs
trie-db/src/sectriedb.rs
trie-db/src/sectriedbmut.rs
trie-db/src/triedb.rs
trie-db/src/triedbmut.rs
trie-db/test/benches/bench.rs
trie-db/test/src/fatdb.rs
trie-db/test/src/fatdbmut.rs
trie-db/test/src/iter_build.rs
trie-db/test/src/iterator.rs
trie-db/test/src/proof.rs
trie-db/test/src/recorder.rs
trie-db/test/src/sectriedb.rs
trie-db/test/src/sectriedbmut.rs
trie-db/test/src/trie_codec.rs
trie-db/test/src/triedb.rs
trie-db/test/src/triedbmut.rs
trie-eip1186/test/src/eip1186.rs

This leads to one extra storage lookup before we are doing the actual key lookup. This leads to reading the `root` twice
when just wanting to lookup one key in the trie. We also return an error on lookup anyway if `root` doesn't exists, so
there is really no need to do this twice.

Do not check for root in `TrieDB` and `TrieDBMut` constructors

---

Cargo.toml
memory-db/CHANGELOG.md
memory-db/Cargo.toml
test-support/trie-bench/CHANGELOG.md
test-support/trie-bench/Cargo.toml
trie-db/test/Cargo.toml
trie-eip1186/test/Cargo.toml

Depends on https://github.com/paritytech/parity-common/pull/680.

memory-db: update parity-util-mem

---

hash256-std-hasher/Cargo.toml
hash256-std-hasher/benches/bench.rs
memory-db/Cargo.toml
memory-db/benches/bench.rs
test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/fuzz/Cargo.toml
trie-db/test/Cargo.toml
trie-db/test/benches/bench.rs
trie-eip1186/Cargo.toml
trie-root/test/Cargo.toml

- update criterion to v0.4.0 (close #165)
- remove some useless dependencies
- close #171

*: update criterion to v0.4.0

---

trie-db/Cargo.toml
trie-db/src/nibble/mod.rs

I'm trying to do some refactoring of the iterators here, and I noticed that the `NibbleVec` technically wastes 4 bytes of space that otherwise could be used. Fixing this might or might not help anything, but it certainly triggers my OCD, so here's a PR that bumps the size so that no bytes are left behind.
The `size_of::<NibbleVec>()` remains unchanged before and after.

Expand `NibbleVec` by 4 bytes (that was previously wasted as padding)

---

test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/CHANGELOG.md
trie-db/Cargo.toml
trie-db/fuzz/Cargo.toml
trie-db/src/iterator.rs
trie-db/src/lib.rs
trie-db/src/nibble/nibblevec.rs
trie-db/src/triedb.rs
trie-db/test/Cargo.toml
trie-db/test/src/triedb.rs
trie-eip1186/Cargo.toml
trie-eip1186/test/Cargo.toml
trie-root/test/Cargo.toml

This PR simplifies and refactors the iterators in `trie-db`.
The changes can be summarized as follows:
* Added `TrieDBNodeIterator`-like `TrieDBRawIterator` and made it lifetimeless (instead of storing a `&TrieDB` it now takes it as a parameter during the iteration)
* `SuspendedTrieDBKeyIterator` was removed since the `TrieDBRawIterator` is a complete replacement for it (with the added bonus that it can be iterated on)
* `TrieDBIterator::next` and `TrieDBKeyIterator::next` were renamed and moved into `TrieDBRawIterator` with no changes to the logic (except making them use `&TrieDB` passed as a parameter instead of the one stored in `self`, and cleaning them up slightly)
* `TrieDBIterator` and `TrieDBKeyIterator` now use `TrieDBRawIterator` under the hood
* A bunch of `#[inline]`s were …

Iterator refactoring

---

test-support/reference-trie/Cargo.toml
test-support/reference-trie/src/lib.rs
test-support/trie-bench/CHANGELOG.md
test-support/trie-bench/Cargo.toml
trie-db/CHANGELOG.md
trie-db/Cargo.toml
trie-db/fuzz/Cargo.toml
trie-db/src/iterator.rs
trie-db/src/trie_codec.rs
trie-db/test/Cargo.toml
trie-eip1186/Cargo.toml
trie-eip1186/test/Cargo.toml
trie-root/test/Cargo.toml

This PR replaces the `Rc` that's returned by the iterators with an `Arc`.
I need this to make the iterators `Send`, which I need for further performance improvements in `substrate`.

Return `Arc` instead of `Rc` from the iterators to make them `Send`

---

hash-db/CHANGELOG.md
hash-db/src/lib.rs
memory-db/CHANGELOG.md
memory-db/Cargo.toml
memory-db/src/lib.rs

This PR switch memorydb to use btreemap internally when used with no_std.
Additionally constrain the Hash of the Hasher to be Ord.

switch no_std map to btreemap

---

trie-db/CHANGELOG.md
trie-db/src/trie_codec.rs
trie-db/test/src/triedb.rs

While working on  https://github.com/cheme/trie/tree/proof_size_tracking, I found that for leaf the hash of detached value was kept in proof.
This pr remove it.
On decode we still overwrite the hash the same way, so this should not need any specific client upgrade (could be an idea later to drop on hash present when it is included in next proof item).
Note that the code is correct for branch already.

remove hash of known value for leaf in compact proof.

---

test-support/reference-trie/CHANGELOG.md
test-support/reference-trie/Cargo.toml
test-support/reference-trie/src/lib.rs
test-support/reference-trie/src/substrate.rs
trie-db/CHANGELOG.md
trie-db/Cargo.toml
trie-db/fuzz/Cargo.toml
trie-db/fuzz/fuzz_targets/prefix_seek_iter.rs
trie-db/fuzz/src/lib.rs
trie-db/src/iterator.rs
trie-db/test/Cargo.toml
trie-db/test/src/triedb.rs

After calling the `TrieDBRawIterator::prefix_then_seek` the iterator is not supposed to return any keys outside of the requested prefix; this unfortunately [is not the case](https://github.com/polkadot-js/apps/issues/9103), and this PR fixes the issue.
- Considering the complexity of the code I didn't completely trust myself to get this right, so I also added a fuzz test for this method. So far it's been running for quite a while and stopped barfing any new errors.
- For the fuzz test and for the tests I've copy-pasted the trie layout code from Substrate. The reference trie here already contains a Substrate-like trie layout, but it's not *exactly* the same. If I'm going to fuzz on something I'd rather do it on exactly the same thing we use in production.
- I only test and fuzz on the trie …

Fix `TrieDBRawIterator::prefix_then_seek`

---

trie-db/src/lookup.rs
trie-db/src/triedbmut.rs
trie-db/test/src/triedbmut.rs

fixes https://github.com/paritytech/trie/issues/197
fix is rather straight forward. An alternative would be to remove lookup for triedbmut as it is not use by substrate and less tested.

fixing triedbmut lookup, added some testing in test.

---

trie-db/src/fatdb.rs
trie-db/src/lib.rs
trie-db/src/lookup.rs
trie-db/src/nibble/nibblevec.rs
trie-db/src/sectriedb.rs
trie-db/src/triedb.rs
trie-db/test/src/triedb.rs

This PR adds support for fetching the merkle value directly from the trie-db.
- Adds `get_closest_merkle_value` on the `Trie` trait
- `TrieDb` iterates over the nibbles of the provided key
- At each iteration DB is queried for the containing node
- last value encountered on the path from the root to the key is returned
- During trie traversal, the internal recorder is updated with trie actions
- This should make other trie queries to the key more efficient
- Test with `HashedValueNoExtThreshold<1>` as trie layout and value update at given key
We could build on this PR to have support for recorded Merkel Value in the cache.
Would love to get your thoughts on this @cheme @arkpar 🙏 
(For reference @tomaka to ensure we don't break anything wrt to compatibilities between smoldot and substrate) …

trie-db: Fetch the closest merkle value

---

trie-db/src/lib.rs
trie-db/src/lookup.rs
trie-db/src/recorder.rs
trie-db/src/triedbmut.rs
trie-db/test/src/triedb.rs

`trie_nodes_recorded_for_key` was not working properly for inline values. It would always return `RecordedForKey::None` while we actually have accessed and recorded all the trie nodes for the value. The pr introduces `TrieAccess::InlineValue` to communicate this access to the recorder properly to make it then return `RecordedForKey::Value`.

Make `trie_nodes_recorded_for_key` work for inline values

---

test-support/reference-trie/Cargo.toml
test-support/trie-bench/CHANGELOG.md
test-support/trie-bench/Cargo.toml
trie-db/CHANGELOG.md
trie-db/Cargo.toml
trie-db/test/Cargo.toml
trie-eip1186/Cargo.toml
trie-eip1186/test/Cargo.toml

This PR prepares the release of trie-db 0.28.0 to allow substrate https://github.com/paritytech/polkadot-sdk/pull/1153 to use the merkle value functionality.
The version has been bumped from 0.27.1 to 0.28.0 since the addition of `lookup_first_descendant` represents a breaking change for the `Trie` trait. 
- Make `trie_nodes_recorded_for_key` work for inline values [#194](https://github.com/paritytech/trie/pull/194)
- trie-db: Fetch the closest merkle value [#199](https://github.com/paritytech/trie/pull/199)
- fixing triedbmut lookup, added some testing in test. [#198](https://github.com/paritytech/trie/pull/198)
@paritytech/subxt-team

chore: Release trie-db 0.28.0

---

trie-db/src/recorder.rs
trie-db/test/src/triedb.rs

We handle `NonExisting` keys as if we have recorded the value. The reason behind this is that we have recorded all the trie nodes to proof that the key doesn't exist in the `trie`. So, next time we want to access the key we can use the `cache` (if present) and do not net to iterate over the trie nodes again.

Fix recorder for `NonExisting` keys

---

trie-db/src/fatdb.rs
trie-db/src/iterator.rs
trie-db/src/lib.rs
trie-db/src/node.rs
trie-db/src/trie_codec.rs
trie-db/src/triedb.rs
trie-db/test/src/double_ended_iterator.rs
trie-db/test/src/iterator.rs
trie-db/test/src/lib.rs
trie-db/test/src/triedb.rs
trie-root/src/lib.rs

Closes https://github.com/paritytech/trie/issues/164
Enables bidirectional iteration by implementing the `DoubleEndedIterator` for all iterator types.
New double ended iterator structs:
- `TrieDBDoubleEndedIterator`
- `TrieDBNodeDoubleEndedIterator`
- `TrieDBKeyDoubleEndedIterator`
- `FatDBDoubleEndedIterator`
Internal iteration methods now accept a `fwd` bool flag to conditionally traverse a trie backwards or forwards (non exhaustive list).
- `TrieDBRawIterator::next_raw_item`
- `TrieDBRawIterator::seek`
- `Crumb::increment` (renamed to `Crumb::step` to better convey its behaviour)
Modifies `next_raw_item` to return middle node (i.e. a node containing child nodes) in reverse order based on iteration direction. Middle node is returned last when iterating backwards, mirroring forward …

Implements `DoubleEndedIterator` for trie iterators

---

trie-db/src/triedbmut.rs

I was working with the lib and realized that `hash_count` property in `TrieDBMut` struct is not used so I opened this PR to remove it.

Remove unused `hash_count`

---

test-support/reference-trie/Cargo.toml
test-support/trie-bench/CHANGELOG.md
test-support/trie-bench/Cargo.toml
trie-db/CHANGELOG.md
trie-db/Cargo.toml
trie-db/test/Cargo.toml
trie-eip1186/Cargo.toml
trie-eip1186/test/Cargo.toml

Releasing 0.29 of trie-db (and trie-bench 0.39).

Release trie-db 0.29.0

---

test-support/reference-trie/src/lib.rs
trie-db/CHANGELOG.md
trie-db/Cargo.toml
trie-db/fuzz/Cargo.toml
trie-db/fuzz/fuzz_targets/double_iter.rs
trie-db/fuzz/src/lib.rs
trie-db/src/iterator.rs
trie-db/src/triedb.rs
trie-db/test/src/double_ended_iterator.rs

@snowmead , this should fix the error you did detect on backend iterator.

Fix backward iterator seek

---

hash-db/src/lib.rs

The HashDB trait mandates its implementors to be Send and Sync. However, since removing this constraint doesn't affect the remaining code, I'm curious if there's a particular reason for retaining it. 
I'm particularly interested in this because I need to implement the HashDB trait for a structure within a single-threaded wasm runtime that isn't Send or Sync.

HashDb trait should not imply Send and Sync

---

test-support/reference-trie/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/CHANGELOG.md
trie-db/Cargo.toml
trie-db/test/Cargo.toml
trie-eip1186/Cargo.toml
trie-eip1186/test/Cargo.toml

Releasing 0.30.0 of trie-db to pick up https://github.com/paritytech/trie/pull/216

Release trie-db 0.30.0

---

test-support/trie-bench/CHANGELOG.md
test-support/trie-bench/Cargo.toml

Trie-bench needs to be released as well because we bumped the trie-db version and will mismatch when updating in substrate.

Release trie-bench 0.40.0

---

memory-db/Cargo.toml
test-support/trie-bench/Cargo.toml
trie-db/fuzz/Cargo.toml
trie-db/test/Cargo.toml
trie-eip1186/test/Cargo.toml

Bump versions for releases to release https://github.com/paritytech/trie/pull/221

prepare crate releases
